os: osx
env: OSX=10.12
osx_image: xcode8.1
install:
- rvm install ruby-2.3.3;
- rvm --default use 2.3.3;

script:
- brew tap barklyprotects/barkly .
- BARKLYTRAVIS=true brew barkly

notifications:
  slack:
    secure: K7vmyuJyoykoaow14XNWScPCV7ahhL+X2qlsaBy9SBsbxD4MlDcnm71wWBVoSFX589kPShiE1cSx3etTnB0yQs88GHooCR0s1s0TjDhDs7cqyw7DEilChuiL47NEw/zUh1EWu1iul+SexpOICvYcM6u1HHb0NghxTvfrkodDfPusXpyhNinc6np+T3HJkI0Ea3A/NTF0j0uSypdOU21qnqy5QGiU2GYo2MJzu9SzcHi322LFJWQPtcuSOyEwDq8PeCdivOe+NnSwA5jyA7iCt7JTilLqBdUPv2k+Mkzz04DEPsPzRsL+eqmQ+j85PJjHFuVqduIhbLUwYf0tNet9jaWaTIRhUwlVlzT6FxiZCSFrXh7rQYkRAyGf/UcNJw52ipkGOjiNiaSfiJzXTqpFbU/5NssiHDKUTgfUiDZcj6VJ0MCtgYn9O8jw/I5pmlTN5oFqn/Bsr1jgxQz3tQo4t1PxPO8kdi8jouxwfksLgIr/JUq4COZrIhCUi4dy86xAC6auKy6pWhIS05Ca2hX60WYe/OWg5CIWWYI+ECzdd3hLjsLN/eG8Kp+p94k7bHKmVsuxJkrv3Tx4Zx9kyiFBB4JaV0a+ekd4XoKE65kP4jM2BuWHXPx16rFTsnU58yzXBEvjchXKioGkmM00FHLIUCJEo0tt8psJiCIzDK3n2x0=
