language: objective-c
matrix:
  include:
  - os: osx
    osx_image: xcode11.2
  # OSX 10.13
  # Unstable
  # - os: osx
    # xcode 9.4 is available but doesn't seem to work well.
    # osx_image: xcode9.3
  # OSX 10.12
  #- os: osx
  #  osx_image: xcode9.2
  # OSX 10.11
  #- os: osx
  #  osx_image: xcode8

script:
- brew update
- brew tap barklyprotects/barkly .
- brew barkly

notifications:
  slack:
    secure: K7vmyuJyoykoaow14XNWScPCV7ahhL+X2qlsaBy9SBsbxD4MlDcnm71wWBVoSFX589kPShiE1cSx3etTnB0yQs88GHooCR0s1s0TjDhDs7cqyw7DEilChuiL47NEw/zUh1EWu1iul+SexpOICvYcM6u1HHb0NghxTvfrkodDfPusXpyhNinc6np+T3HJkI0Ea3A/NTF0j0uSypdOU21qnqy5QGiU2GYo2MJzu9SzcHi322LFJWQPtcuSOyEwDq8PeCdivOe+NnSwA5jyA7iCt7JTilLqBdUPv2k+Mkzz04DEPsPzRsL+eqmQ+j85PJjHFuVqduIhbLUwYf0tNet9jaWaTIRhUwlVlzT6FxiZCSFrXh7rQYkRAyGf/UcNJw52ipkGOjiNiaSfiJzXTqpFbU/5NssiHDKUTgfUiDZcj6VJ0MCtgYn9O8jw/I5pmlTN5oFqn/Bsr1jgxQz3tQo4t1PxPO8kdi8jouxwfksLgIr/JUq4COZrIhCUi4dy86xAC6auKy6pWhIS05Ca2hX60WYe/OWg5CIWWYI+ECzdd3hLjsLN/eG8Kp+p94k7bHKmVsuxJkrv3Tx4Zx9kyiFBB4JaV0a+ekd4XoKE65kP4jM2BuWHXPx16rFTsnU58yzXBEvjchXKioGkmM00FHLIUCJEo0tt8psJiCIzDK3n2x0=
