#!/bin/bash

HOMEBREWBARKLYCMDDIR=$(dirname $0)
cd $HOMEBREWBARKLYCMDDIR/..
HOMEBREWBARKLYDIR=$(pwd -P)
. "$HOMEBREWBARKLYDIR/lib/init.sh"

echo "Starting barkly brew setup..."

if [ -d "$HOME/cylent" ]; then
  echo "Using existing cylent directory."
  # Do nothing if link already exists
  if ! [ -h "$HOME/barkly" ]; then
    echo "Symlinking barkly dir"
    ln -sv "$HOME/cylent" "$HOME/barkly"
  fi
  export BARKLYDIR="$HOME/cylent"
else
  echo "Using barkly home directory."
  mkdir -p "$HOME/barkly"
  if ! [ -h "$HOME/cylent"]; then
    echo "Creating cylent symlink for now."
    ln -sv "$HOME/barkly" "$HOME/cylent"
  fi
  export BARKLYDIR="$HOME/barkly"
fi

if ! [ -e "$BARKLYDIR/projects" ]; then
  echo "Projects file not found!"
  echo "Creating and populating with base."
  echo "base" > $BARKLYDIR/projects
fi

echo "Running setup for each project..."
while read PROJECT; do
  echo "Starting setup for $PROJECT"
  echo "Starting brew installation..."
  echo
  brew bundle --file="$HOMEBREWBARKLYDIR/projects/$PROJECT/Brewfile"
  echo
  echo "Cloning Repos"
  echo
  clonerepos "$HOMEBREWBARKLYDIR/projects/$PROJECT/repos"
  echo
  echo "Running additional setup"
  "$HOMEBREWBARKLYDIR/projects/$PROJECT/setup.sh"
  echo
  echo "Done."
done < $BARKLYDIR/projects
