#!/bin/bash

HOMEBREWBARKLYCMDDIR=$(dirname $0)
cd $HOMEBREWBARKLYCMDDIR/..
HOMEBREWBARKLYDIR=$(pwd -P)


echo "Starting barkly brew setup..."

if [ -d "$HOME/cylent" ]; then
  echo "Using existing cylent directory."
  # Do nothing if link already exists
  if ! [ -h "$HOME/barkly" ]; then
    echo "Symlinking barkly dir"
    ln -sv "$HOME/cylent" "$HOME/barkly"
  fi
  export BARKLYDIR="$HOME/cylent"
else
  echo "Using barkly home directory."
  mkdir -p "$HOME/barkly"
  export BARKLYDIR="$HOME/barkly"
fi

if ! [ -e "$BARKLYDIR/projects" ]; then
  echo "Projects file not found!"
  echo "Creating and populating with base."
  echo "base" > $BARKLYDIR/projects
fi

echo "Running setup for each project..."
while read PROJECT; do
  echo "Starting setup for $PROJECT"
  "$HOMEBREWBARKLYDIR/projects/$PROJECT/setup.sh"
  echo "Done."
done < $BARKLYDIR/projects
