#!/bin/bash

HOMEBREWBARKLYCMDDIR=$(dirname $0)
cd $HOMEBREWBARKLYCMDDIR/..
export HOMEBREWBARKLYDIR=$(pwd -P)
. "$HOMEBREWBARKLYDIR/lib/init.sh"

log "Starting barkly brew setup..."

if [ -d "$HOME/cylent" ]; then
  log "Using existing cylent directory."
  # Do nothing if link already exists
  if ! [ -h "$HOME/barkly" ]; then
    logn "Symlinking barkly dir:"
    ln -sv "$HOME/cylent" "$HOME/barkly"
    logk
  fi
  export BARKLYDIR="$HOME/cylent"
else
  log "Using barkly home directory."
  mkdir -p "$HOME/barkly"
  if ! [ -h "$HOME/cylent"]; then
    logn "Creating cylent symlink for now:"
    ln -sv "$HOME/barkly" "$HOME/cylent"
    logk
  fi
  export BARKLYDIR="$HOME/barkly"
fi

if ! [ -e "$BARKLYDIR/projects" ]; then
  log "Projects file not found!"
  logn "Creating and populating with base:"
  echo "base" > $BARKLYDIR/projects
  logk
fi

log "Running setup for each project..."
while read PROJECT; do
  log "Starting setup for $PROJECT"
  log "Starting brew installation..."
  brew bundle --file="$HOMEBREWBARKLYDIR/projects/$PROJECT/Brewfile"
  logk
  log "Cloning Repos for $PROJECT"
  clonerepos "$HOMEBREWBARKLYDIR/projects/$PROJECT/repos"
  logk
  log "Running additional setup for $PROJECT"
  "$HOMEBREWBARKLYDIR/projects/$PROJECT/setup.sh"
  logk
done < $BARKLYDIR/projects
